eureka:
  instance:
    preferIpAddress: true
  client:
      serviceUrl:
        defaultZone: http://192.168.99.100:8080/eureka/v2/
spring:
  application:
    name: discovery-eureka
  main:
    banner-mode: "off"
server:
  port: 8001