eureka:
  instance:
    preferIpAddress: true
  client:
      serviceUrl:
        defaultZone: http://eureka:8080/eureka/v2/
spring:
  application:
    name: sleuth-service2
  sleuth:
    sampler:
      percentage: 1
  cloud:
    stream:
      binder:
        kafka:
          brokers: 192.168.99.100
          defaultBrokerPort: 9092
          zkNodes: 192.168.99.100
          defaultZkPort: 2181
server:
  port: 8000