version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: app
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 5432

  app:
    image: jeanblanchard/java
    ports:
      - 8000
    volumes:
      - ./build/libs:/code
    links:
        - postgres:db
    depends_on:
        - postgres
    command: java -jar -Dspring.profiles.active=qa /code/jdbc-1.0-SNAPSHOT.jar

  integrationTests:
    image: niaquinto/gradle
    volumes:
      - .:/usr/bin/app
      - $HOME/.gradle/caches:/root/.gradle/caches
    links:
        - postgres:db
    depends_on:
        - postgres
        - app
    command: integrationTests