version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: app
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 5432

  app:
    image: niaquinto/gradle
    ports:
      - 8000
    volumes:
      - .:/usr/bin/app
      - $HOME/.gradle/caches:/root/.gradle/caches
    links:
        - postgres:db
    depends_on:
        - postgres
    entrypoint: ""
    command: java -jar -Dspring.profiles.active=dev /usr/bin/app/build/libs/jdbc-1.0-SNAPSHOT.jar