mysql:
  image: openzipkin/zipkin-mysql:1.30.2
  ports:
    - 3306:3306

kafka:
  image: flozano/kafka:0.9.0.0
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: "192.168.99.100"
    ADVERTISED_PORT: "9092"

eureka:
  image: netflixoss/eureka:1.3.1
  ports:
     - "8080:8080"

service1:
  image: jeanblanchard/java
  ports:
    - "8000:8000"
  volumes:
    - ./service1/build/libs:/code
  links:
      - eureka
  command: java -jar /code/service1-1.0-SNAPSHOT.jar

service2:
  image: jeanblanchard/java
  ports:
      - "8001:8000"
  volumes:
      - ./service2/build/libs:/code
  links:
      - eureka
  command: java -jar /code/service2-1.0-SNAPSHOT.jar

zipkinconsumer:
  image: jeanblanchard/java
  ports:
      - "9411:9411"
  volumes:
      - ./../zipkin-consumer/build/libs:/code
  command: java -jar /code/zipkin-consumer-1.0-SNAPSHOT.jar


zipkinui:
  image: openzipkin/zipkin-web
  ports:
    - "8081:8080"
  environment:
    QUERY_PORT_9411_TCP_ADDR: zipkinquery
    ROOTURL: "/"
  links:
    - zipkinconsumer:zipkinquery